export const Project = [
  {
    id: 7,
    date: "May' 2025 - Aug' 2025",
    name: "Logsy",
    img: [
      "https://i.postimg.cc/gkS1y8PG/logsy1.png",
      "https://i.postimg.cc/L8G7wSX7/logsy2.png",
      "https://i.postimg.cc/yYYwSntf/logsy3.png",
      "https://i.postimg.cc/Z5W2wnTp/logsy4.png",
    ],
    description: `Logsy is a real-time log monitoring and alerting system designed for developers and small teams. It streams application logs through Kafka, processes them for storage and alerting, and provides an interactive dashboard for viewing live logs, server metrics, and error alerts. Built to be lightweight and developer-friendly, Logsy helps quickly identify issues, analyze trends, and maintain system reliability`,
    techstack: [
      "SPRING BOOT",
      "GO",
      "NODE JS",
      "TYPESCRIPT",
      "SOCKET.IO",
      "KAFKA",
      "MONGODB",
      "REMIX",
      "TAILWIND CSS",
    ],
    link: "",
    repo: "https://github.com/vanamuthuV/logsy",
    private: false,
    isdiscontinued: false,
    isBackend: true,
    dockerimage: null,
  },

  {
    id: 1,
    date: "Sep' 2024 - Mar' 2025",
    name: "ResumeTweaker",
    img: [
      "https://i.postimg.cc/xCKpTvWF/resumetweaker1.png",
      "https://i.postimg.cc/jq4mgzBq/resumetweaker2.png",
      "https://i.postimg.cc/cChzvSft/resumetweaker3.png",
      "https://i.postimg.cc/zBn61WBj/resumetweaker4.png",
    ],
    description: `ResumeTweaker is a smart resume builder that helps users create polished resumes with customizable templates and real-time previews. It features AI-powered resume reviews and mock interview modules to boost user readiness and job application success.`,
    techstack: [
      "NEXT JS",
      "TAILWIND CSS",
      "SHADCN",
      "NODE JS",
      "EXPRESS JS",
      "PRISMA ORM",
      "POSTGRESQL",
    ],
    link: "https://resumetweaker.vercel.app",
    repo: " ",
    private: true,
    isdiscontinued: false,
    isBackend: false,
    dockerimage: null,
  },

  {
    id: 4,
    name: "Attendance Management",
    date: "Feb' 2024 - Mar' 2024",
    img: [
      "https://i.postimg.cc/GpTS6wzR/attendace1.png",
      "https://i.postimg.cc/25YnKBsm/attendace2.png",
      "https://i.postimg.cc/6QhCJpKZ/attendace3.png",
    ],
    description: `An intuitive web-based Attendance Management System designed for seamless database integration, enabling basic CRUD operations. The application allows users to efficiently add, update, and delete student records, as well as take and view attendance.`,
    techstack: ["REACT", "NODE JS", "EXPRESS JS", "POSTGRESQL"],
    link: "https://my-attendence.vercel.app/",
    repo: "https://github.com/vanamuthuV/My-Attendence",
    private: false,
    isdiscontinued: false,
    isBackend: false,
    dockerimage: null,
  },

  {
    id: 2,
    name: "Inkwellify",
    date: "Nov' 2023 - Feb' 2024",
    img: [
      "https://i.postimg.cc/PxGFj3Fw/inkwellify1.png",
      "https://i.postimg.cc/057P8M3h/inkwellify2.png",
      "https://i.postimg.cc/L5FSt2qy/inkwellify3.png",
      "https://i.postimg.cc/qR306z7h/inkwellify4.png",
    ],
    description: `Inkwellify is a versatile blogging platform that allows users to
            upload daily content and engage interactively. Users can like,
            comment on, and bookmark posts, as well as follow their favorite
            authors to stay updated with their latest contributions.`,
    texchstack: ["REACT JS", "MUI", "NODE JS", "EXPRESS JS", "POSTGRESQL"],
    link: "https://inkwellify.vercel.app/",
    repo: "https://github.com/vanamuthuV/BlogSpot",
    private: false,
    isdiscontinued: false,
    isBackend: false,
    dockerimage: null,
  },

  {
    id: 3,
    date: "Jun' 2023 - Nov' 2023",
    name: "AniWatch",
    img: [
      "https://i.postimg.cc/yxsQJJK6/aniwatch1.png",
      "https://i.postimg.cc/Gm0N7qzf/aniwatch2.png",
      "https://i.postimg.cc/pV6382jR/aniwatch3.png",
    ],
    description: `AniWatch is a dynamic platform dedicated to showcasing the latest anime releases in the industry. Built entirely with React and leveraging robust API integration, AniWatch offers users up-to-date information on new anime series and films, ensuring they stay informed about the latest trends and releases.`,
    techstack: ["NODE JS", "API INTEGRATION", "AXIOS"],
    link: "https://www-aniwatch-com.netlify.app/",
    repo: "https://github.com/vanamuthuV/aniwatch",
    private: false,
    isdiscontinued: false,
    isBackend: false,
    dockerimage: null,
  },

  {
    id: 5,
    date: "Nov' 2022 - Jan' 2023",
    name: "Apple Arcade Clone",
    img: ["https://i.postimg.cc/GtKMvc3F/applearcade.png"],
    description: `Apple Arcade is a website featuring a custom-designed landing page, created using HTML and CSS. The landing page showcases a clean and modern design that captures the essence of the Apple Arcade experience, highlighting key features and engaging visitors effectively.`,
    techstack: ["HTML", "CSS", "RESPONSIVE"],
    link: "https://glittering-chaja-23943b.netlify.app/",
    repo: "https://github.com/vanamuthuV/AppleArcade",
    private: false,
    isdiscontinued: false,
    isBackend: false,
    dockerimage: null,
  },

  {
      id: 6,
      date: "Jun' 2024 - Aug' 2024",
    name: "LinkHub ( Discontinued )",
    img: ["https://i.postimg.cc/D059LBvp/linkhub.png"],
    description: `LinkHub is a web platform that allows users to centralize all their links in one place, providing a streamlined way to manage and share them. It features click analytics, enabling users to track link performance and gain insights into user engagement.`,
    techstack: ["REACT", "REDUX", "PRISMA", "NODE JS", "EXPRESS JS", "PGSQL"],
    link: "https://nexalink.vercel.app/",
    repo: "https://github.com/vanamuthuV/linkhub",
    private: false,
    isdiscontinued: true,
    isBackend: false,
    dockerimage: null,
  },
];
